[package]
name = "ldk-sample"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>", "Antoine Riard <antoine.riard@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
bitcoin = "0.24"
bitcoin-bech32 = "0.7"
lightning = { git = "https://github.com/jkczyz/rust-lightning", rev = "a9aeeb21d62aac6257ec7ca2a808bb3fd9445c5b" }
lightning-net-tokio = { git = "https://github.com/jkczyz/rust-lightning", rev = "a9aeeb21d62aac6257ec7ca2a808bb3fd9445c5b" }
lightning-block-sync = { git = "https://github.com/jkczyz/rust-lightning", rev = "a9aeeb21d62aac6257ec7ca2a808bb3fd9445c5b", features = ["rpc-client", "rest-client"] }
lightning-invoice = { git = "https://github.com/TheBlueMatt/rust-lightning-invoice", rev = "86f1dd0" }
lightning-persister = { git = "https://github.com/jkczyz/rust-lightning", rev = "a9aeeb21d62aac6257ec7ca2a808bb3fd9445c5b" }
hyper = "0.13"
serde = "1"
serde_json = "1"
rand = "0.4"
futures-util = "0.3"
tokio = { version = "1.0", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "time", "sync"] }
base64 = "0.9"
time = "0.2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "ldk-node"
path = "src/init.rs"

[[bin]]
name = "ldk-cli"
path = "src/sample-cli.rs"

[lib]
name = "ldk"
path = "src/lib.rs"
